kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalog-example
  namespace: acs-rox
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-example
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catalog-example
    spec:
      containers:
        - name: httpd
          image: 'registry.redhat.io/rhel8/httpd-24:1-209'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
