kind: Job
apiVersion: batch/v1
metadata:
  name: test-job
  namespace: acs-rox
spec:
  template:
    metadata:
      name: argotest
      namespace: acs-rox
    spec:
      containers:
        - name: argotest
          image: registry.access.redhat.com/ubi8/ubi-minimal:8.6-902.1661794353
          env:
          - name: ACS_ADMIN_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: central-htpasswd
                key: password
          - name: CENTRAL
            value: https://central-acs-rox.apps.pmo-sno7.pmo.ocp.philmoses.com:443
          command:
            - /bin/bash
            - '-c'
            - |
              echo "hello my friend"
      restartPolicy: Never
