apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  creationTimestamp: "2021-05-02T20:35:28Z"
  finalizers:
  - argoproj.io/finalizer
  generation: 3
  labels:
    app: vplugin-demo
    operation: Update
  name: vplugin-demo
  namespace: vplugin-demo
spec:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
  controller:
    processors: {}
  dex:
    openShiftOAuth: true
  grafana:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  ha:
    enabled: false
  image: quay.io/pbmoses/pmo-argovault
  initialSSHKnownHosts: {}
  prometheus:
    enabled: false
    ingress:
      enabled: false
    route:
      enabled: false
  rbac: {}
  redis: {}
  repo:
    mountsatoken: true
    serviceaccount: vplugin
  server:
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
    service:
      type: ""
  tls:
    ca: {}
  version: latest
