apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
  name: exsecretsdemo
  namespace: vault-demo
spec:
  backendType: vault
  data:
    - key: secret/data/vault-demo-secret1
      name: password
      property: password
  vaultMountPoint: kubernetes
  vaultRole: exsecretsdemo
